// swift-tools-version: 5.9
import PackageDescription

// WalkMe iOS SDK 0.2.3
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMe",
    products: [
        .library(name: "WalkMe", targets: ["WalkMe"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMe",
            url: "https://github.com/WalkMe-int/walkme-ios-sdk/releases/download/0.2.3/WalkMe.xcframework.zip",
            checksum: "b0ef24b62ba6bb0e8b968d8b50ae36c6b74722d5345bd9e319d78de1438f8280"
        )
    ]
)
