// swift-tools-version: 5.9
import PackageDescription

// WalkMe iOS SDK 1.1.3
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMe",
    products: [
        .library(name: "WalkMe", targets: ["WalkMe"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMe",
            url: "https://github.com/WalkMe-int/walkme-ios-sdk/releases/download/1.1.3/WalkMe.xcframework.zip",
            checksum: "d6a42976f48f928f741c051c4c4207e11ea6aefaa371571c131035e5bade6f91"
        )
    ]
)
