// swift-tools-version: 5.9
import PackageDescription

// WalkMe iOS SDK 0.2.0
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMe",
    products: [
        .library(name: "WalkMe", targets: ["WalkMe"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMe",
            url: "https://github.com/WalkMe-int/walkme-ios-sdk/releases/download/0.2.0/WalkMe.xcframework.zip",
            checksum: "037f07fa76f668aabd72032247e67f53141ad22c2bc799e9500682dedf03f65a"
        )
    ]
)
